# action.yml
name: 'PagedJS - CLI'
description: 'Takes an arbitrary URL and returns a paginated PDF as a result'
inputs:
  target_url:  # id of input
    description: 'Target URL'
    required: true
    default: 'https://policy.cookalliance.org/introduction/'
  additional_script:
    description: 'PagedJS handlers'
    required: false
runs:
  using: 'docker'
  image: 'docker://andyayrey/pagedjs-cli:latest'
  args:
    - "'${{ inputs.target_url }}'  --additional-script '${{ inputs.additional_script }}'"